### ISSUE TITLE
K8s 1.13.1 - PersistentVolume is not a supported volume type for snapshots

### ISSUE THREAD

**Issue by riptidewave93** [StackPointCloud/ark-plugin-digitalocean#9]
DigitalOcean Kubernetes Version = 1.13.1-do.2
ark-plugin-digitalocean Version = latest (I assume v0.10.0)
ark binary version = v0.10.0

Issue:
I defined a basic backup policy for the namespace of "default". The config I used is below:

```
ark schedule create default-ns-backup --snapshot-volumes=true --include-namespaces default --schedule "0 1 * * *" --ttl 504h0m0s
```

I then noticed that while metadata is being backed up to my space, volume snapshots are not getting generated. I checked the logs for the ark pod, and noticed the following:

```
time="2018-12-23T20:03:21Z" level=info msg="Backing up resource" backup=heptio-ark/default-ns-backup-20181223200301 group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:163" name=pvc-4110714b-06d1-11e9-a3a7-56dbe60cd656 namespace=default
time="2018-12-23T20:03:21Z" level=info msg="Executing takePVSnapshot" backup=heptio-ark/default-ns-backup-20181223200301 group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:378" name=pvc-4110714b-06d1-11e9-a3a7-56dbe60cd656 namespace=default
time="2018-12-23T20:03:21Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=heptio-ark/default-ns-backup-20181223200301 group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:406" name=pvc-4110714b-06d1-11e9-a3a7-56dbe60cd656 namespace=default
time="2018-12-23T20:03:21Z" level=error msg="Error getting block store for volume snapshot location" backup=heptio-ark/default-ns-backup-20181223200301 error="unable to locate BlockStore plugin named digitalocean-blockstore" group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:417" name=pvc-4110714b-06d1-11e9-a3a7-56dbe60cd656 namespace=default volumeSnapshotLocation="&{{VolumeSnapshotLocation ark.heptio.com/v1} {default  heptio-ark /apis/ark.heptio.com/v1/namespaces/heptio-ark/volumesnapshotlocations/default 86d3a1a7-06b8-11e9-a3a7-56dbe60cd656 3240 1 2018-12-23 13:42:01 +0000 UTC <nil> <nil> map[] map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"ark.heptio.com/v1\",\"kind\":\"VolumeSnapshotLocation\",\"metadata\":{\"annotations\":{},\"name\":\"default\",\"namespace\":\"heptio-ark\"},\"spec\":{\"provider\":\"digitalocean-blockstore\"}}\n] [] nil [] } {digitalocean-blockstore map[]} {}}"
time="2018-12-23T20:03:21Z" level=info msg="PersistentVolume is not a supported volume type for snapshots, skipping." backup=heptio-ark/default-ns-backup-20181223200301 group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:442" name=pvc-4110714b-06d1-11e9-a3a7-56dbe60cd656 namespace=default
```

What I used to setup ark in my environment:

```
curl -fsSL -o /tmp/ark-prereq.yaml https://raw.githubusercontent.com/StackPointCloud/ark-plugin-digitalocean/master/examples/00-prereqs.yaml \
	&& kubectl apply -f /tmp/ark-prereq.yaml \
	&& rm /tmp/ark-prereq.yaml
kubectl apply -f ./Prod-Configs/Prod-ark.yaml
ark plugin add quay.io/stackpoint/ark-blockstore-digitalocean:latest
```

A copy of my Prod-ark.yaml is attached; with sensitive info removed.

**Comment by riptidewave93** [comment]
Seems I can't attach my config as a file; so here is the copy of the contents:

```
---
apiVersion: v1
data:
  cloud: bmljZXRyeQ==
  digitalocean_token: bmljZXRyeQ==
kind: Secret
metadata:
  name: cloud-credentials
  namespace: heptio-ark
type: Opaque
---
apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: heptio-ark
spec:
  provider: aws
  objectStorage:
    bucket: not-a-bucket
  config:
    region: sfo2
    s3Url: https://sfo2.digitaloceanspaces.com
---
apiVersion: ark.heptio.com/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: heptio-ark
spec:
  provider: digitalocean-blockstore
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: heptio-ark
  name: ark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: ark
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"
    spec:
      restartPolicy: Always
      serviceAccountName: ark
      containers:
        - name: ark
          image: gcr.io/heptio-images/ark:latest
          command:
            - /ark
          args:
            - server
            - --default-volume-snapshot-locations=digitalocean-blockstore:default
          volumeMounts:
            - name: cloud-credentials
              mountPath: /credentials
            - name: plugins
              mountPath: /plugins
            - name: scratch
              mountPath: /scratch
          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: ARK_SCRATCH_DIR
              value: /scratch
            - name: DIGITALOCEAN_TOKEN
              valueFrom:
                secretKeyRef:
                  key: digitalocean_token
                  name: cloud-credentials
      volumes:
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
        - name: plugins
          emptyDir: {}
        - name: scratch
          emptyDir: {}
```
